#!/bin/bash

## rstudio ##
wget http://download2.rstudio.org/rstudio-server-pro-0.98.976-amd64.deb
sudo dpkg -i rstudio-server-pro-0.98.976-amd64.deb
sudo apt-get -f --force-yes --yes install

# create self-signed cert
sudo openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=WA/L=Richland/O=PNNL/CN=bootcamp.pnnl.gov" -keyout /etc/rstudio/server.key  -out /etc/rstudio/server.crt

sudo chmod 600 /etc/rstudio/server.*

echo "www-port=443" | sudo tee -a /etc/rstudio/rserver.conf
echo "ssl-enabled=1" | sudo tee -a /etc/rstudio/rserver.conf
echo "ssl-certificate=/etc/rstudio/server.crt" | sudo tee -a /etc/rstudio/rserver.conf
echo "ssl-certificate-key=/etc/rstudio/server.key" | sudo tee -a /etc/rstudio/rserver.conf

sudo rstudio-server restart
