#!/usr/bin/env bash
################################################################################
# Author: Ashrith Barthur
# Date: 19/06/2014
# This is a script to install and configure additional things that require
# the running of Hadoop, HDFS. The condition to test the existence of HDFS is to
# if the standard /mnt directory exist. 
# v0.1 - pushing HDFS /tmp, /user/user3 and chmod configurations to this script
# so that it does not have to be attempted manually after EMR initialization.
################################################################################

echo "#!/usr/bin/env bash" >/tmp/fireup.sh
echo "	if [ \"/home/hadoop/bin/hadoop fs -test -d /mnt\" ]; then" >>/tmp/fireup.sh
echo "		/home/hadoop/bin/hadoop fs -mkdir /user/user3" >>/tmp/fireup.sh
echo "		/home/hadoop/bin/hadoop fs -mkdir /tmp" >>/tmp/fireup.sh
echo "		/home/hadoop/bin/hadoop fs -chmod -R 777 /" >>/tmp/fireup.sh
echo "		sudo -u shiny nohup shiny-server &" >>/tmp/fireup.sh
# Anything you would like to add (configurations or installations) that require Hadoop, HDFS to be running
# use a shell script format and enter after this comment, preferably before the empty crontab entry.
# PLEASE TAKE CARE OF BASHISMS, AMAZON AMI BASH IS NOT STANDARD BASH

echo "		echo \"\" >/tmp/crontab.txt">>/tmp/fireup.sh
echo "		crontab /tmp/crontab.txt" >>/tmp/fireup.sh
echo "	fi" >>/tmp/fireup.sh
chmod +x /tmp/fireup.sh


echo "*/1 * * * * export JAVA_HOME=/usr/lib/jvm/java-7-oracle; /tmp/fireup.sh" >/tmp/crontab.txt
crontab /tmp/crontab.txt
