#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
	USER_COUNT=1
else
	USER_COUNT=$1
fi

echo "USER_COUNT=$USER_COUNT"
# give hadoop a password
echo "hadoop:hadoop" | sudo chpasswd

# start shiny
# start manually!
# sudo -u shiny nohup shiny-server &

sudo -E -u hadoop /home/hadoop/bin/hadoop fs -mkdir /tmp

#download data & scripts
wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/nf-week2.csv
wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/nf-week2-sample.csv
wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/activity1.2.R
wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/activity1.3.R
wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/activity2.R
wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/activity3.R
wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/activity4.R

#create users
USER_COUNT=$1
PORT=52900
for i in $(eval echo "{1..$USER_COUNT}")
  do
	  # create user
	  sudo useradd -m bootcamp-user-$i
	  # give them a password
	  echo "bootcamp-user-$i:bootcamp2014" | sudo chpasswd
	  # create data dir in hadoop
  	  sudo -E -u hadoop /home/hadoop/bin/hadoop fs -mkdir /user/bootcamp-user-$i/vast/raw/nf
	  # put the data in hdfs
	  sudo -E -u hadoop /home/hadoop/bin/hadoop fs -put nf-week2.csv /user/bootcamp-user-$i/vast/raw/nf
	  # change perms
	  sudo -E -u hadoop /home/hadoop/bin/hadoop fs -chown -R bootcamp-user-$i /user/bootcamp-user-$i
	  # copy scripts and sample data to user home dir
	  sudo cp nf-week2-sample.csv activity* /home/bootcamp-user-$i
	  sudo chown -R bootcamp-user-$i /home/bootcamp-user-$i
	  # increment the trelliscope port
	  PORT=$[PORT + 1]
	  echo "TR_PORT=$PORT" | sudo tee -a /home/bootcamp-user-$i/.Renviron
	  echo "HDFS_USER_VAST=/user/bootcamp-user-$i/vast" | sudo tee -a /home/bootcamp-user-$i/.Renviron
 done

# rwx to the entire world
sudo -E -u hadoop /home/hadoop/bin/hadoop fs -chmod -R 777 /
