#!/bin/bash

### INSTALL R ###
# ## REMOVE old R ##
dpkg --get-selections | grep r-base | awk '{print $1}' | xargs sudo apt-get --yes autoremove

# setup repo
echo "deb http://cran.rstudio.com/bin/linux/debian squeeze-cran3/" | sudo tee -a /etc/apt/sources.list
gpg --keyserver pgpkeys.mit.edu --recv-key 06F90DE5381BA480
gpg -a --export 06F90DE5381BA480 | sudo apt-key add -

# install 3.1
sudo apt-get --yes update
sudo -E apt-get -t squeezecran3.0 --yes --force-yes install r-base-core=3.1.0-1~squeezecran3.0
sudo -E apt-get -t squeezecran3.0 --yes --force-yes install r-base-dev=3.1.0-1~squeezecran3.0
sudo chmod -R aou=rwx /usr/local/lib/R/site-library

##########################################################
## You only need to run this code to update emr-binaries
##########################################################


# packages need updating
# sudo su - -c "R -e \"install.packages('codetools', repos='http://cran.rstudio.com/')\""
# sudo su - -c "R -e \"install.packages('lattice', repos='http://cran.rstudio.com/')\""
# sudo su - -c "R -e \"install.packages('MASS', repos='http://cran.rstudio.com/')\""
# sudo su - -c "R -e \"install.packages('boot', repos='http://cran.rstudio.com/')\""
# sudo su - -c "R -e \"install.packages('nnet', repos='http://cran.rstudio.com/')\""
# sudo su - -c "R -e \"install.packages('cluster', repos='http://cran.rstudio.com/')\""

# some other required packages

## rjava ##
# sudo R CMD javareconf
# wget http://cran.r-project.org/src/contrib/rJava_0.9-6.tar.gz
# sudo R CMD INSTALL rJava_0.9-6.tar.gz

## shiny package ##
# sudo su - -c "R -e \"install.packages('shiny', repos='http://cran.rstudio.com/')\""

## took 2 minutes
