#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    echo "[start user number] [end user number]"
	exit;
else
    # USER_COUNT=$1
    START_NO=$1
    END_NO=$2
fi

# echo "USER_COUNT=$USER_COUNT"
echo "START=$START_NO END=$END_NO"

# give hadoop a password
# echo "hadoop:hadoop" | sudo chpasswd

# start shiny
# start manually!
# sudo -u shiny nohup shiny-server &

# sudo -E -u hadoop /home/hadoop/bin/hadoop fs -mkdir /tmp

#download data & scripts
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_1.2.R
# #wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_1.2_solutions.R
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_1.3.R
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_1.3_solutions.R
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_1.4.R
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_1.4_solutions.R
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_1.5.R
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_1.5_solutions.R
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_2.1.R
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_2.2.R
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/Activity_2.3.R
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/dailycount.Rdata
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/nf-week2-sample.csv
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/nf-week2.csv
# wget --no-check-certificate https://s3-us-west-2.amazonaws.com/velocity1/vast-data/some_fake_data.csv

#create users
# USER_COUNT=$1
PORT=5290$START_NO
echo $PORT

for i in $(eval echo "{$START_NO..$END_NO}")
  do
      echo "adding bootcamp-user-$i on port $PORT"
      
      # create user
      sudo useradd -m bootcamp-user-$i
      # give them a password
      echo "bootcamp-user-$i:bootcamp2014-$i" | sudo chpasswd
      # create data dir in hadoop
      sudo -E -u hadoop /home/hadoop/bin/hadoop fs -mkdir /user/bootcamp-user-$i/vast/raw/nf
      # put the data in hdfs
      sudo -E -u hadoop /home/hadoop/bin/hadoop fs -put nf-week2.csv /user/bootcamp-user-$i/vast/raw/nf
      # change perms
      sudo -E -u hadoop /home/hadoop/bin/hadoop fs -chown -R bootcamp-user-$i /user/bootcamp-user-$i
      # copy scripts and sample data to user home dir
      sudo cp nf-week2-sample.csv activity* Activity* dailycount.Rdata some_* /home/bootcamp-user-$i
      # create R lib directory
      sudo mkdir -p /home/bootcamp-user-$i/R/lib
      # give everyone persmissions
      sudo chown -R bootcamp-user-$i /home/bootcamp-user-$i
      # set some R environment variables
      echo "TR_PORT=$PORT" | sudo tee -a /home/bootcamp-user-$i/.Renviron
      echo "HDFS_USER_VAST=/user/bootcamp-user-$i/vast" | sudo tee -a /home/bootcamp-user-$i/.Renviron
	  # increment the trelliscope port
	  PORT=$[PORT + 1]
 done


