#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    echo "[start user number] [end user number]"
	exit;
else
    # USER_COUNT=$1
    START_NO=$1
    END_NO=$2
fi

# echo "USER_COUNT=$USER_COUNT"
echo "START=$START_NO END=$END_NO"

#create users
# USER_COUNT=$1

for i in $(eval echo "{$START_NO..$END_NO}")
  do
      echo "user $i"
      # add command here
      # sudo cp <some file> /home/bootcamp-user-$i
      # sudo chown -R bootcamp-user-$i /home/bootcamp-user-$i
 done


